#!/bin/bash
# Author: Luis Alberto Mayta  <slovacus@gmail.com>
# https://github.com/luismayta/Hooks-git/

EXTENSIONS_REGEX="(.css$|.js$|.png$|.jpg$|.bmp$|.gif$)"
ULTIMO_COMMIT=$(git rev-list --max-count=1 HEAD)
PENULTIMO_COMMIT=$(git rev-list --max-count=1 HEAD~1)
FILES=$(git diff $ULTIMO_COMMIT $PENULTIMO_COMMIT --name-only)
echo -e "$FILES"

for FILE in $FILES; do
	if [[ $FILE =~ $EXTENSIONS_REGEX ]]; then
		RESULT="true"
	fi
done

echo -e "$RESULT" 
if [ "$RESULT" == "true" ]; then
	git log -1 --format=%h > src/last_commit
	git add .
	git commit -m "update last_commit" --no-verify
	echo -e "se actualizo File last_commit." 
    exit 0
fi

