#!/bin/bash
# author @slovacus -> Luis Alberto Mayta
# modified by @jansanchez -> Jan Sanchez A.
#
declare -a EXTENSION=('*.css' '*.js' '*.png' '*.jpg' '*.gif');
ULTIMO_COMMIT=$(git rev-list --max-count=1 HEAD)
PENULTIMO_COMMIT=$(git rev-list --max-count=1 HEAD~1)
FILES=$(git diff $ULTIMO_COMMIT $PENULTIMO_COMMIT --name-only)
RESULT="false"
COMMITFILE="last_commit"
#echo -e ""
#echo -e "$FILES"

for FILE in $FILES; do
	if [ "$FILE" == "$COMMITFILE" ] ; then	
		break
	fi
	for I in "${EXTENSION[@]}"; do
		if [[ $FILE = ${I} ]]; then
			if [[ $FILE = ${EXTENSION[0]} ]]; then # si el archivo es css entonces reemplazara el texto version
				IDCOMMIT=$(set -f; git log -1 --format=%h)
				sed -i "s/version/v=$IDCOMMIT/g" $FILE
				echo -e ""
				echo "reemplazando version dentro del css"
				echo -e ""
			fi
			#echo "extension estatica detectada - - - > ${I}"
			RESULT="true"
		fi
	done
done

if [ "$RESULT" == "true" ] ; then
	IDCOMMIT=$(set -f; git log -1 --format=%h)
	git log -1 --format=%h > last_commit
	git add .
	git commit -m "update $COMMITFILE to: $IDCOMMIT" --no-verify
	echo -e ""
	echo -e "update $COMMITFILE to: $IDCOMMIT"
	echo -e ""
	exit 0
fi