#!/usr/bin/env python

"""
Git pre-commit hook for checking code php instructions

Author:
    Luis Alberto Mayta

"""

VERSION = '0.1.0'

import argparse
import sys
import commit_hook

def main():
    """ Main functions handling configuration files etc"""

    result = commit_hook.check_repo()

if __name__ == '__main__':
    main()
    sys.exit(0)

sys.exit(1)
